## Part 1: Preprocessing

In [24]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras import layers

#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head()

Age Attrition     BusinessTravel              Department  DistanceFromHome  \
0   41       Yes      Travel_Rarely                   Sales                 1   
1   49        No  Travel_Frequently  Research & Development                 8   
2   37       Yes      Travel_Rarely  Research & Development                 2   
3   33        No  Travel_Frequently  Research & Development                 3   
4   27        No      Travel_Rarely  Research & Development                 2   

   Education EducationField  EnvironmentSatisfaction  HourlyRate  \
0          2  Life Sciences                        2          94   
1          1  Life Sciences                        3          61   
2          2          Other                        4          92   
3          4  Life Sciences                        4          56   
4          1        Medical                        1          40   

   JobInvolvement  ...  PerformanceRating RelationshipSatisfaction  \
0               3  ...                  3                        1   
1               2  ...                  4                        4   
2               2  ...                  3                        2   
3               3  ...                  3                        3   
4               3  ...                  3                        4   

   StockOptionLevel TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  \
0                 0                 8                      0               1   
1                 1                10                      3               3   
2                 0                 7                      3               3   
3                 0                 8                      3               3   
4                 1                 6                      3               3   

   YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0               6                   4                        0   
1              10                   7                        1   
2               0                   0                        0   
3               8                   7                        3   
4               2                   2                        2   

   YearsWithCurrManager  
0                     5  
1                     7  
2                     0  
3                     0  
4                     2  

[5 rows x 27 columns]

In [25]:
# Determine the number of unique values in each column.
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [26]:
# Create y_df with the Attrition and Department columns





# Create a new DataFrame 'y_df' containing only 'Attrition' and 'Department' columns
y_df = attrition_df[['Attrition', 'Department']]
# Display the first 5 rows to verify the result
y_df.head()




Attrition              Department
0       Yes                   Sales
1        No  Research & Development
2       Yes  Research & Development
3        No  Research & Development
4        No  Research & Development

In [27]:
# Create a list of at least 10 column names to use as X data
x_columns = ['Age', 'JobSatisfaction', 'OverTime', 'DistanceFromHome',
             'Education', 'NumCompaniesWorked', 'EnvironmentSatisfaction',
             'HourlyRate', 'JobInvolvement', 'PerformanceRating']

# Create X_df using your selected columns
X_df = attrition_df[x_columns]

# Show the data types for X_df

print(X_df.dtypes)





Age                         int64
JobSatisfaction             int64
OverTime                   object
DistanceFromHome            int64
Education                   int64
NumCompaniesWorked          int64
EnvironmentSatisfaction     int64
HourlyRate                  int64
JobInvolvement              int64
PerformanceRating           int64
dtype: object


In [28]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split



# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_df, y_df, test_size=0.2, random_state=42)

# Verify the shape of the resulting datasets
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)



X_train shape: (1176, 10)
X_test shape: (294, 10)
y_train shape: (1176, 2)
y_test shape: (294, 2)


In [29]:
# Convert your X data to numeric data types however you see fit
# Add new code cells as necessary

from sklearn.preprocessing import OneHotEncoder

# Convert training data to numeric types
OverTime_encoder = OneHotEncoder (sparse_output=False, drop='first', handle_unknown='ignore')
OverTime_encoder.fit(np.array(X_train['OverTime']).reshape(-1, 1))
X_train ['OverTimeEncoder'] = OverTime_encoder.transform(np.array(X_train['OverTime']).reshape(-1, 1))
X_test ['OverTimeEncoder'] = OverTime_encoder.transform(np.array(X_test['OverTime']).reshape(-1, 1))


X_train = X_train.drop(columns=['OverTime'])
X_test = X_test.drop(columns=['OverTime'])


print(X_train.dtypes)
print(X_test.dtypes)



Age                          int64
JobSatisfaction              int64
DistanceFromHome             int64
Education                    int64
NumCompaniesWorked           int64
EnvironmentSatisfaction      int64
HourlyRate                   int64
JobInvolvement               int64
PerformanceRating            int64
OverTimeEncoder            float64
dtype: object
Age                          int64
JobSatisfaction              int64
DistanceFromHome             int64
Education                    int64
NumCompaniesWorked           int64
EnvironmentSatisfaction      int64
HourlyRate                   int64
JobInvolvement               int64
PerformanceRating            int64
OverTimeEncoder            float64
dtype: object


In [30]:
# Create a StandardScaler


# Fit the StandardScaler to the training data


# Scale the training and testing data






from sklearn.preprocessing import StandardScaler

# Create a StandardScaler
scaler = StandardScaler()

# Fit the StandardScaler to the training data
scaler.fit(X_train)

# Scale the training and testing data
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Verify the shapes of the scaled data
print("X_train_scaled shape:", X_train_scaled.shape)
print("X_test_scaled shape:", X_test_scaled.shape)




X_train_scaled shape: (1176, 10)
X_test_scaled shape: (294, 10)


In [31]:
# Create a OneHotEncoder for the Department column


# Fit the encoder to the training data


# Create two new variables by applying the encoder
# to the training and testing data





from sklearn.preprocessing import OneHotEncoder

# Convert training data to numeric types
Attrition_encoder = OneHotEncoder (sparse_output=False, drop= None, handle_unknown='ignore')
Attrition_encoder.fit(np.array(y_train['Attrition']).reshape(-1, 1))
y_attrition_train = Attrition_encoder.transform(np.array(y_train['Attrition']).reshape(-1, 1))
y_attrition_test = Attrition_encoder.transform(np.array(y_test['Attrition']).reshape(-1, 1))


display(y_attrition_train)
display(y_attrition_test)






array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [0., 1.],
       [1., 0.],
       [1., 0.]])

array([[1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.

In [23]:
# Create a OneHotEncoder for the Attrition column


# Fit the encoder to the training data


# Create two new variables by applying the encoder
# to the training and testing data




from sklearn.preprocessing import OneHotEncoder

# Convert training data to numeric types
department_encoder = OneHotEncoder (sparse_output=False, drop= None, handle_unknown='ignore')
department_encoder.fit(np.array(y_train['Department']).reshape(-1, 1))
y_department_train = department_encoder.transform(np.array(y_train['Department']).reshape(-1, 1))
y_department_test = department_encoder.transform(np.array(y_test['Department']).reshape(-1, 1))


display(y_department_train)
display(y_department_test)







array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       ...,
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0

## Create, Compile, and Train the Model

In [33]:
# Find the number of columns in the X training data
number_input_features = len(X_train.columns)
number_input_features

# Create the input layer
input = layers.Input(shape=(number_input_features,))

# Create at least two shared layers
share1 = layers.Dense(units=64, activation='relu')(input)
share2 = layers.Dense(units=128, activation='relu')(share1)

In [34]:
# Create a branch for Department
# with a hidden layer and an output layer

# Create the hidden layer
department_hidden = layers.Dense(units=64, activation='relu', name='department_hidden')(share2)


# Create the output layer
department_output = layers.Dense(y_department_train.shape[1], activation='sigmoid' , name='department_output')(department_hidden)


In [37]:
# Create a branch for Attrition
# with a hidden layer and an output layer

# Create the hidden layer
attrition_hidden = layers.Dense(units=64, activation='relu', name='attrition_hidden')(share2)
# Create the output layer
attrition_output = layers.Dense(y_attrition_train.shape[1], activation='sigmoid', name='attrition_output')(attrition_hidden)

In [40]:
# Create the model
model= Model(inputs=input, outputs=[attrition_output, department_output])

# Compile the model
model.compile(optimizer='adam', loss={'attrition_output': 'binary_crossentropy', 'department_output': 'categorical_crossentropy'}, 
              metrics={'attrition_output': 'accuracy', 'department_output': 'accuracy'})



# Summarize the model
model.summary()



Model: "functional_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)              ┃ Output Shape           ┃        Param # ┃ Connected to           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━┩
│ input_layer_1             │ (None, 10)             │              0 │ -                      │
│ (InputLayer)              │                        │                │                        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_2 (Dense)           │ (None, 64)             │            704 │ input_layer_1[0][0]    │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_3 (Dense)           │ (None, 128)            │          8,320 │ dense_2[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ attrition_hidden (Dense)  │ (None, 64)             │          8,256 │ dense_3[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ department_hidden (Dense) │ (None, 64)             │          8,256 │ dense_3[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ attrition_output (Dense)  │ (None, 2)              │            130 │ attrition_hidden[0][0] │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ department_output (Dense) │ (None, 3)              │            195 │ department_hidden[0][… │
└───────────────────────────┴────────────────────────┴────────────────┴────────────────────────┘

 Total params: 25,861 (101.02 KB)

 Trainable params: 25,861 (101.02 KB)

 Non-trainable params: 0 (0.00 B)

In [48]:
# Train the model

fit_model = model.fit(X_train_scaled,  {'department_output': y_department_train, 'attrition_output': y_attrition_train}, epochs=100, verbose=1)








Epoch 1/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.9555 - attrition_output_loss: 0.1282 - department_output_accuracy: 0.9474 - department_output_loss: 0.1735 - loss: 0.3018
Epoch 2/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.9542 - attrition_output_loss: 0.1421 - department_output_accuracy: 0.9877 - department_output_loss: 0.0541 - loss: 0.1962
Epoch 3/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - attrition_output_accuracy: 0.9827 - attrition_output_loss: 0.0430 - department_output_accuracy: 0.9981 - department_output_loss: 0.0263 - loss: 0.0693
Epoch 4/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.9935 - attrition_output_loss: 0.0116 - department_output_accuracy: 0.9992 - department_output_loss: 0.0123 - loss: 0.0239
Epoch 5/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 1.0000 - attrition_output_loss: 0.0050 - department_output_accuracy: 1.0000 - department_output_loss: 0.

In [45]:
# Evaluate the model with the testing data
test_results = model.evaluate(X_test_scaled, {'department_output': y_department_test , 'attrition_output': y_attrition_test})



10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - attrition_output_accuracy: 0.7899 - attrition_output_loss: 1.7881 - department_output_accuracy: 0.5055 - department_output_loss: 2.9693 - loss: 4.7420 


In [46]:
# Print the accuracy for both department and attrition
print(f"Department Accuracy: {test_results[3]*100:.2f}%")
print(f"Attrition Accuracy: {test_results[4]*100:.2f}%")

Department Accuracy: 81.29%
Attrition Accuracy: 53.40%


# Summary

In the provided space below, briefly answer the following questions.


1. Is accuracy the best metric to use on this data? Why or why not?


2. What activation functions did you choose for your output layers, and why?


3. Can you name a few ways that this model might be improved?


YOUR ANSWERS HERE

1.ccuracy may not be the best metric for this dataset, especially if the data is imbalanced (e.g., significantly more "No" than "Yes" in the Attrition column or uneven distribution across Department categories). In such cases, accuracy can be misleading, as the model might predict the majority class correctly most of the time while failing to capture the minority class effectively. Instead, metrics such as precision, recall, F1-score, or the ROC-AUC score may provide a better understanding of the model's performance, especially for the Attrition output where imbalanced data is often common.

2.What activation functions did you choose for your output layers, and why?
The sigmoid function, which is ideal for binary classification problems.

3. Can you name a few ways that this model might be improved?
Use class weights in the model during training to give more importance to the minority class. 
Adjust hyperparameters such as the number of layers, units per layer, learning rate, and batch size using methods like Grid Search or Random Search.